### ISSUE TITLE
Compilation errors while deploying

### ISSUE THREAD

**Issue by haruotsa** [seemoo-lab/chirpotle#2]
Hi again! I'm following the step-by-step basic configuration example and I'm stuck at the deployment.
The cross compiler fails during the compilation of "chirpotle-companion" for "native" with MCU "native".
Errors:
`arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-fdiagnostics-color’
arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-Wformat-overflow’
arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-Wformat-truncation’`

Is this related to the version of the cross-compiler?

Here's some data of my system:
uname -a
`4.15.0-117-generic #118~16.04.1-Ubuntu SMP Sat Sep 5 23:35:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

arm-linux-gnueabihf-gcc -v
`COLLECT_GCC=arm-linux-gnueabihf-gcc
COLLECT_LTO_WRAPPER=/home/.../tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../libexec/gcc/arm-linux-gnueabihf/4.8.3/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: /cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/.build/src/gcc-linaro-4.8-2014.01/configure --build=i686-build_pc-linux-gnu --host=i686-build_pc-linux-gnu --target=arm-linux-gnueabihf --prefix=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/install --with-sysroot=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/install/arm-linux-gnueabihf/libc --enable-languages=c,c++,fortran --disable-multilib --enable-multiarch --with-arch=armv6 --with-tune=arm1176jz-s --with-fpu=vfp --with-float=hard --with-pkgversion='crosstool-NG linaro-1.13.1-4.8-2014.01 - Linaro GCC 2013.11' --with-bugurl=https://bugs.launchpad.net/gcc-linaro --enable-__cxa_atexit --enable-libmudflap --enable-libgomp --enable-libssp --with-gmp=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/.build/arm-linux-gnueabihf/build/static --with-mpfr=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/.build/arm-linux-gnueabihf/build/static --with-mpc=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/.build/arm-linux-gnueabihf/build/static --with-isl=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/.build/arm-linux-gnueabihf/build/static --with-cloog=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/.build/arm-linux-gnueabihf/build/static --with-libelf=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/.build/arm-linux-gnueabihf/build/static --enable-threads=posix --disable-libstdcxx-pch --enable-linker-build-id --enable-plugin --enable-gold --with-local-prefix=/cbuild/slaves/oorts/crosstool-ng/builds/arm-linux-gnueabihf-raspbian-linux/install/arm-linux-gnueabihf/libc --enable-c99 --enable-long-long --with-float=hard
Thread model: posix
gcc version 4.8.3 20140106 (prerelease) (crosstool-NG linaro-1.13.1-4.8-2014.01 - Linaro GCC 2013.11) `

**Comment by haruotsa** [comment]
Ok, I upgraded the cross compiler to 8.3 and the error vanished. 8.3 seems to be the gcc version on the latest Rasbian. 
Perhaps add a version check of the cross compiler to the installer script?

**Comment by fhessel** [comment]
Thanks for the feedback and debugging info. I think the following steps would make sense to make the framework more portable:

- As the `native-raspi` is only relevant if you actually want to deploy to such a device, I'll modify the framework so that it will only be built if you use such a device.
- I'll add proper cross-compilers and libraries for Raspbian as another submodule, similar to the ones for xtensa/ESP32. That should also cover issues where `libc` versions differ and so on.
- I'll add some GitHub actions that will try a build of the modules on each commit, to see if it fails on plain Ubuntu. That should help identifying most issues caused by implicit assumptions about tools and their versions in the target env.

**Comment by haruotsa** [comment]
Today I was able make the nodes communicate with each other by the basic example. However, I did start over with a clean Lubuntu 20.04 VM as the coreutils of my original machine were too old ("/usr/bin/env: invalid option -- 'S'). 

For some reason I was not able to build and flash the example firmware with the latest repo, but with the one I started with few days ago.

**Comment by fhessel** [comment]
> For some reason I was not able to build and flash the example firmware with the latest repo, but with the one I started with few days ago.

Could you tell me how you're trying to flash the firmware right now? I'm currently changing the dependency management so that you only need to install the toolchains for tools that you actually use in the configuration which you've picked (so if you run `chirpotle deploy --conf test` and `test` only contains a LoPy4, it will no longer try to build versions for Raspberry Pi and Feather M0). So to re-build all firmwares, you now need to call `chirpotle.sh deploy --conf test --build-all`.

Would something like `chirpotle.sh flash lopy4-uart /dev/ttyACM0` as a standalone command help you?

For the Raspberry Pi cross-compile, I doubt that I can do much more than a GCC version check, because [raspberrypi/tools](https://github.com/raspberrypi/tools) doesn't seem to receive updates anymore. But with the updated dependency management, that shouldn't raise too much trouble any more.

**Comment by fhessel** [comment]
It should now work out of the box with a somewhat recent Debian or Ubuntu as base. Ubuntu 18.04 and 20.04 are also tested on each push to the main branch, and for the latest commits, [these tests seem to be successful](https://github.com/seemoo-lab/chirpotle/runs/1994627533).

Relying on the distribution's GCC versions worked somewhat well for Debian (as it is also the foundation for Raspbian/Raspberry Pi OS), but to get it running with Ubuntu I needed to use a separate toolchain, which will now be downloaded and installed in the project folder under `tools` the first time your try to build a firmware for such an architecture.

Do you think the problems you had are addressed with that?

**Comment by haruotsa** [comment]
> Could you tell me how you're trying to flash the firmware right now? I'm currently changing the dependency management so that you only need to install the toolchains for tools that you actually use in the configuration which you've picked (so if you run `chirpotle deploy --conf test` and `test` only contains a LoPy4, it will no longer try to build versions for Raspberry Pi and Feather M0). So to re-build all firmwares, you now need to call `chirpotle.sh deploy --conf test --build-all`.

At the moment I'm really just following the front page setup guide from ground up. Only difference to the setup guide is that I have pycom expansion boards instead of usb-ttl converters to flash the boards. I guess my main problem was just some incompatibility problems with cross-compiler (& associated libraries), which led to failures during the build. 
 
> Would something like `chirpotle.sh flash lopy4-uart /dev/ttyACM0` as a standalone command help you?
> 
As I can live with the manual flashing, the current deployment script works well.

**Comment by haruotsa** [comment]
> Do you think the problems you had are addressed with that?

I'll test the latest repo shortly and comment here how it goes.

**Comment by haruotsa** [comment]
Hi, I was able to reproduce the basic configuration with my setup using the latest repo.
